/* ===========================================================================
   places.js — wereldwijde plaatsenlijst met IANA-tijdzones.
   {n:naam, c:land, lat, lon, z:IANA-zone, r:regio}
   Onbekende plaats? De invoer laat handmatige coördinaten + zone toe.
=========================================================================== */
(function () {
  const CITIES = [
    // België
    { n: 'Brussel', c: 'België', lat: 50.85, lon: 4.35, z: 'Europe/Brussels', r: 'België' },
    { n: 'Antwerpen', c: 'België', lat: 51.22, lon: 4.40, z: 'Europe/Brussels', r: 'België' },
    { n: 'Gent', c: 'België', lat: 51.05, lon: 3.72, z: 'Europe/Brussels', r: 'België' },
    { n: 'Brugge', c: 'België', lat: 51.21, lon: 3.22, z: 'Europe/Brussels', r: 'België' },
    { n: 'Leuven', c: 'België', lat: 50.88, lon: 4.70, z: 'Europe/Brussels', r: 'België' },
    { n: 'Hasselt', c: 'België', lat: 50.93, lon: 5.34, z: 'Europe/Brussels', r: 'België' },
    { n: 'Luik', c: 'België', lat: 50.63, lon: 5.57, z: 'Europe/Brussels', r: 'België' },
    { n: 'Charleroi', c: 'België', lat: 50.41, lon: 4.44, z: 'Europe/Brussels', r: 'België' },
    // Nederland
    { n: 'Amsterdam', c: 'Nederland', lat: 52.37, lon: 4.90, z: 'Europe/Amsterdam', r: 'Nederland' },
    { n: 'Rotterdam', c: 'Nederland', lat: 51.92, lon: 4.48, z: 'Europe/Amsterdam', r: 'Nederland' },
    { n: 'Den Haag', c: 'Nederland', lat: 52.08, lon: 4.31, z: 'Europe/Amsterdam', r: 'Nederland' },
    { n: 'Utrecht', c: 'Nederland', lat: 52.09, lon: 5.12, z: 'Europe/Amsterdam', r: 'Nederland' },
    { n: 'Eindhoven', c: 'Nederland', lat: 51.44, lon: 5.48, z: 'Europe/Amsterdam', r: 'Nederland' },
    { n: 'Groningen', c: 'Nederland', lat: 53.22, lon: 6.57, z: 'Europe/Amsterdam', r: 'Nederland' },
    { n: 'Maastricht', c: 'Nederland', lat: 50.85, lon: 5.69, z: 'Europe/Amsterdam', r: 'Nederland' },
    // Europa
    { n: 'Londen', c: 'VK', lat: 51.51, lon: -0.13, z: 'Europe/London', r: 'Europa' },
    { n: 'Parijs', c: 'Frankrijk', lat: 48.86, lon: 2.35, z: 'Europe/Paris', r: 'Europa' },
    { n: 'Berlijn', c: 'Duitsland', lat: 52.52, lon: 13.40, z: 'Europe/Berlin', r: 'Europa' },
    { n: 'Madrid', c: 'Spanje', lat: 40.42, lon: -3.70, z: 'Europe/Madrid', r: 'Europa' },
    { n: 'Barcelona', c: 'Spanje', lat: 41.39, lon: 2.17, z: 'Europe/Madrid', r: 'Europa' },
    { n: 'Lissabon', c: 'Portugal', lat: 38.72, lon: -9.14, z: 'Europe/Lisbon', r: 'Europa' },
    { n: 'Rome', c: 'Italië', lat: 41.90, lon: 12.50, z: 'Europe/Rome', r: 'Europa' },
    { n: 'Milaan', c: 'Italië', lat: 45.46, lon: 9.19, z: 'Europe/Rome', r: 'Europa' },
    { n: 'Zürich', c: 'Zwitserland', lat: 47.37, lon: 8.54, z: 'Europe/Zurich', r: 'Europa' },
    { n: 'Wenen', c: 'Oostenrijk', lat: 48.21, lon: 16.37, z: 'Europe/Vienna', r: 'Europa' },
    { n: 'Dublin', c: 'Ierland', lat: 53.35, lon: -6.26, z: 'Europe/Dublin', r: 'Europa' },
    { n: 'Kopenhagen', c: 'Denemarken', lat: 55.68, lon: 12.57, z: 'Europe/Copenhagen', r: 'Europa' },
    { n: 'Stockholm', c: 'Zweden', lat: 59.33, lon: 18.06, z: 'Europe/Stockholm', r: 'Europa' },
    { n: 'Oslo', c: 'Noorwegen', lat: 59.91, lon: 10.75, z: 'Europe/Oslo', r: 'Europa' },
    { n: 'Helsinki', c: 'Finland', lat: 60.17, lon: 24.94, z: 'Europe/Helsinki', r: 'Europa' },
    { n: 'Warschau', c: 'Polen', lat: 52.23, lon: 21.01, z: 'Europe/Warsaw', r: 'Europa' },
    { n: 'Praag', c: 'Tsjechië', lat: 50.08, lon: 14.44, z: 'Europe/Prague', r: 'Europa' },
    { n: 'Boedapest', c: 'Hongarije', lat: 47.50, lon: 19.04, z: 'Europe/Budapest', r: 'Europa' },
    { n: 'Athene', c: 'Griekenland', lat: 37.98, lon: 23.73, z: 'Europe/Athens', r: 'Europa' },
    { n: 'Istanbul', c: 'Turkije', lat: 41.01, lon: 28.98, z: 'Europe/Istanbul', r: 'Europa' },
    { n: 'Moskou', c: 'Rusland', lat: 55.76, lon: 37.62, z: 'Europe/Moscow', r: 'Europa' },
    { n: 'Kyiv', c: 'Oekraïne', lat: 50.45, lon: 30.52, z: 'Europe/Kyiv', r: 'Europa' },
    // Afrika
    { n: 'Caïro', c: 'Egypte', lat: 30.04, lon: 31.24, z: 'Africa/Cairo', r: 'Afrika' },
    { n: 'Casablanca', c: 'Marokko', lat: 33.57, lon: -7.59, z: 'Africa/Casablanca', r: 'Afrika' },
    { n: 'Algiers', c: 'Algerije', lat: 36.75, lon: 3.06, z: 'Africa/Algiers', r: 'Afrika' },
    { n: 'Tunis', c: 'Tunesië', lat: 36.81, lon: 10.18, z: 'Africa/Tunis', r: 'Afrika' },
    { n: 'Lagos', c: 'Nigeria', lat: 6.52, lon: 3.38, z: 'Africa/Lagos', r: 'Afrika' },
    { n: 'Accra', c: 'Ghana', lat: 5.60, lon: -0.19, z: 'Africa/Accra', r: 'Afrika' },
    { n: 'Dakar', c: 'Senegal', lat: 14.69, lon: -17.44, z: 'Africa/Dakar', r: 'Afrika' },
    { n: 'Nairobi', c: 'Kenia', lat: -1.29, lon: 36.82, z: 'Africa/Nairobi', r: 'Afrika' },
    { n: 'Addis Abeba', c: 'Ethiopië', lat: 9.03, lon: 38.74, z: 'Africa/Addis_Ababa', r: 'Afrika' },
    { n: 'Johannesburg', c: 'Zuid-Afrika', lat: -26.20, lon: 28.05, z: 'Africa/Johannesburg', r: 'Afrika' },
    { n: 'Kaapstad', c: 'Zuid-Afrika', lat: -33.92, lon: 18.42, z: 'Africa/Johannesburg', r: 'Afrika' },
    // Midden-Oosten
    { n: 'Dubai', c: 'VAE', lat: 25.20, lon: 55.27, z: 'Asia/Dubai', r: 'Midden-Oosten' },
    { n: 'Tel Aviv', c: 'Israël', lat: 32.08, lon: 34.78, z: 'Asia/Jerusalem', r: 'Midden-Oosten' },
    { n: 'Riyad', c: 'Saoedi-Arabië', lat: 24.71, lon: 46.68, z: 'Asia/Riyadh', r: 'Midden-Oosten' },
    { n: 'Teheran', c: 'Iran', lat: 35.69, lon: 51.39, z: 'Asia/Tehran', r: 'Midden-Oosten' },
    { n: 'Bagdad', c: 'Irak', lat: 33.31, lon: 44.36, z: 'Asia/Baghdad', r: 'Midden-Oosten' },
    { n: 'Beiroet', c: 'Libanon', lat: 33.89, lon: 35.50, z: 'Asia/Beirut', r: 'Midden-Oosten' },
    // Azië
    { n: 'Peking', c: 'China', lat: 39.90, lon: 116.41, z: 'Asia/Shanghai', r: 'Azië' },
    { n: 'Shanghai', c: 'China', lat: 31.23, lon: 121.47, z: 'Asia/Shanghai', r: 'Azië' },
    { n: 'Guangzhou', c: 'China', lat: 23.13, lon: 113.26, z: 'Asia/Shanghai', r: 'Azië' },
    { n: 'Chengdu', c: 'China', lat: 30.57, lon: 104.07, z: 'Asia/Shanghai', r: 'Azië' },
    { n: 'Ürümqi', c: 'China', lat: 43.83, lon: 87.62, z: 'Asia/Shanghai', r: 'Azië' },
    { n: 'Hongkong', c: 'China', lat: 22.32, lon: 114.17, z: 'Asia/Hong_Kong', r: 'Azië' },
    { n: 'Taipei', c: 'Taiwan', lat: 25.03, lon: 121.57, z: 'Asia/Taipei', r: 'Azië' },
    { n: 'Tokio', c: 'Japan', lat: 35.68, lon: 139.69, z: 'Asia/Tokyo', r: 'Azië' },
    { n: 'Osaka', c: 'Japan', lat: 34.69, lon: 135.50, z: 'Asia/Tokyo', r: 'Azië' },
    { n: 'Seoel', c: 'Zuid-Korea', lat: 37.57, lon: 126.98, z: 'Asia/Seoul', r: 'Azië' },
    { n: 'Busan', c: 'Zuid-Korea', lat: 35.18, lon: 129.08, z: 'Asia/Seoul', r: 'Azië' },
    { n: 'Singapore', c: 'Singapore', lat: 1.35, lon: 103.82, z: 'Asia/Singapore', r: 'Azië' },
    { n: 'Bangkok', c: 'Thailand', lat: 13.76, lon: 100.50, z: 'Asia/Bangkok', r: 'Azië' },
    { n: 'Jakarta', c: 'Indonesië', lat: -6.21, lon: 106.85, z: 'Asia/Jakarta', r: 'Azië' },
    { n: 'Manila', c: 'Filipijnen', lat: 14.60, lon: 120.98, z: 'Asia/Manila', r: 'Azië' },
    { n: 'Kuala Lumpur', c: 'Maleisië', lat: 3.14, lon: 101.69, z: 'Asia/Kuala_Lumpur', r: 'Azië' },
    { n: 'Hanoi', c: 'Vietnam', lat: 21.03, lon: 105.85, z: 'Asia/Bangkok', r: 'Azië' },
    { n: 'Ho Chi Minhstad', c: 'Vietnam', lat: 10.82, lon: 106.63, z: 'Asia/Ho_Chi_Minh', r: 'Azië' },
    { n: 'New Delhi', c: 'India', lat: 28.61, lon: 77.21, z: 'Asia/Kolkata', r: 'Azië' },
    { n: 'Mumbai', c: 'India', lat: 19.08, lon: 72.88, z: 'Asia/Kolkata', r: 'Azië' },
    { n: 'Bangalore', c: 'India', lat: 12.97, lon: 77.59, z: 'Asia/Kolkata', r: 'Azië' },
    { n: 'Kolkata', c: 'India', lat: 22.57, lon: 88.36, z: 'Asia/Kolkata', r: 'Azië' },
    { n: 'Karachi', c: 'Pakistan', lat: 24.86, lon: 67.01, z: 'Asia/Karachi', r: 'Azië' },
    { n: 'Dhaka', c: 'Bangladesh', lat: 23.81, lon: 90.41, z: 'Asia/Dhaka', r: 'Azië' },
    { n: 'Kathmandu', c: 'Nepal', lat: 27.72, lon: 85.32, z: 'Asia/Kathmandu', r: 'Azië' },
    { n: 'Colombo', c: 'Sri Lanka', lat: 6.93, lon: 79.86, z: 'Asia/Colombo', r: 'Azië' },
    { n: 'Ulaanbaatar', c: 'Mongolië', lat: 47.89, lon: 106.91, z: 'Asia/Ulaanbaatar', r: 'Azië' },
    { n: 'Almaty', c: 'Kazachstan', lat: 43.24, lon: 76.89, z: 'Asia/Almaty', r: 'Azië' },
    // Oceanië
    { n: 'Sydney', c: 'Australië', lat: -33.87, lon: 151.21, z: 'Australia/Sydney', r: 'Oceanië' },
    { n: 'Melbourne', c: 'Australië', lat: -37.81, lon: 144.96, z: 'Australia/Melbourne', r: 'Oceanië' },
    { n: 'Brisbane', c: 'Australië', lat: -27.47, lon: 153.03, z: 'Australia/Brisbane', r: 'Oceanië' },
    { n: 'Perth', c: 'Australië', lat: -31.95, lon: 115.86, z: 'Australia/Perth', r: 'Oceanië' },
    { n: 'Auckland', c: 'Nieuw-Zeeland', lat: -36.85, lon: 174.76, z: 'Pacific/Auckland', r: 'Oceanië' },
    { n: 'Wellington', c: 'Nieuw-Zeeland', lat: -41.29, lon: 174.78, z: 'Pacific/Auckland', r: 'Oceanië' },
    // Amerika
    { n: 'New York', c: 'VS', lat: 40.71, lon: -74.01, z: 'America/New_York', r: 'Amerika' },
    { n: 'Los Angeles', c: 'VS', lat: 34.05, lon: -118.24, z: 'America/Los_Angeles', r: 'Amerika' },
    { n: 'Chicago', c: 'VS', lat: 41.88, lon: -87.63, z: 'America/Chicago', r: 'Amerika' },
    { n: 'Houston', c: 'VS', lat: 29.76, lon: -95.37, z: 'America/Chicago', r: 'Amerika' },
    { n: 'Miami', c: 'VS', lat: 25.76, lon: -80.19, z: 'America/New_York', r: 'Amerika' },
    { n: 'San Francisco', c: 'VS', lat: 37.77, lon: -122.42, z: 'America/Los_Angeles', r: 'Amerika' },
    { n: 'Toronto', c: 'Canada', lat: 43.65, lon: -79.38, z: 'America/Toronto', r: 'Amerika' },
    { n: 'Vancouver', c: 'Canada', lat: 49.28, lon: -123.12, z: 'America/Vancouver', r: 'Amerika' },
    { n: 'Montreal', c: 'Canada', lat: 45.50, lon: -73.57, z: 'America/Toronto', r: 'Amerika' },
    { n: 'Mexico-Stad', c: 'Mexico', lat: 19.43, lon: -99.13, z: 'America/Mexico_City', r: 'Amerika' },
    { n: 'Bogotá', c: 'Colombia', lat: 4.71, lon: -74.07, z: 'America/Bogota', r: 'Amerika' },
    { n: 'Lima', c: 'Peru', lat: -12.05, lon: -77.04, z: 'America/Lima', r: 'Amerika' },
    { n: 'Santiago', c: 'Chili', lat: -33.45, lon: -70.67, z: 'America/Santiago', r: 'Amerika' },
    { n: 'Buenos Aires', c: 'Argentinië', lat: -34.60, lon: -58.38, z: 'America/Argentina/Buenos_Aires', r: 'Amerika' },
    { n: 'São Paulo', c: 'Brazilië', lat: -23.55, lon: -46.63, z: 'America/Sao_Paulo', r: 'Amerika' },
    { n: 'Rio de Janeiro', c: 'Brazilië', lat: -22.91, lon: -43.17, z: 'America/Sao_Paulo', r: 'Amerika' },
    { n: 'Caracas', c: 'Venezuela', lat: 10.48, lon: -66.90, z: 'America/Caracas', r: 'Amerika' },
    { n: 'Havana', c: 'Cuba', lat: 23.11, lon: -82.37, z: 'America/Havana', r: 'Amerika' },
  ];
  window.QP = window.QP || {};
  window.QP.places = CITIES;
})();
